=== frechilla/blockem/package/debian/usr/share/blockem/challenges/blockem_challenge.dtd
<!ELEMENT blockem_challenge (board, opponent, challenger, infochallenge?)>
<!ATTLIST blockem_challenge name CDATA #REQUIRED>
<!ELEMENT board (nrows, ncolumns)>
    <!ELEMENT nrows (#PCDATA)>
    <!ELEMENT ncolumns (#PCDATA)>
<!ELEMENT opponent (taken*)>
<!ELEMENT challenger (taken*, piece*, starting_row?, starting_col?)>
    <!ELEMENT taken EMPTY>
    <!ATTLIST taken 
        row CDATA #REQUIRED
        col CDATA #REQUIRED>
    <!ELEMENT piece (#PCDATA)>
    <!ATTLIST piece
        available CDATA #REQUIRED>
    <!ELEMENT starting_row (#PCDATA)>
    <!ELEMENT starting_col (#PCDATA)>    
<!ELEMENT infochallenge (author?, email?, description?)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT description (#PCDATA)>

=== frechilla/blockem/src/tests/challengetest/challenge_challenger_no.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE blockem_challenge SYSTEM "blockem_challenge.dtd">

<blockem_challenge name="tmpl: Example 1">
    
    <board>

        <nrows>14</nrows>
        <ncolumns>14</ncolumns>
    </board>
  
    <opponent>
        <taken row="4"  col="4"/>
        <taken row="5"  col="5"/>
        <taken row="10" col="10"/>
    </opponent>
    
    <!-- 
        challenger is always active, "active" tag can't be used as in 
        "opponent"
        
        MISSING
    -->

</blockem_challenge>
