=== frechilla/blockem/challenges/blockem_challenge.dtd
<!ELEMENT blockem_challenge (board, opponent, challenger)>
<!ATTLIST blockem_challenge name CDATA #REQUIRED>
<!ELEMENT board (rows, columns)>
    <!ELEMENT rows (#PCDATA)>
    <!ELEMENT columns (#PCDATA)>
<!ELEMENT opponent (taken*, piece+, starting_row?, starting_col?)>
<!ATTLIST opponent active CDATA #REQUIRED>
<!ELEMENT challenger (taken*, piece+, starting_row, starting_col)>
    <!ELEMENT taken EMPTY>
    <!ATTLIST taken 
        row CDATA #REQUIRED
        col CDATA #REQUIRED>
    <!ELEMENT piece (#PCDATA)>
    <!ATTLIST piece
        available CDATA #REQUIRED>
    <!ELEMENT starting_row (#PCDATA)>
    <!ELEMENT starting_col (#PCDATA)>

=== frechilla/blockem/challenges/example_challenge3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE blockem_challenge SYSTEM "blockem_challenge.dtd">

<!--
    There is no real need for the previous line (locate the .dtd for this .xml
    file)
-->

<!--
    Attribute "name" MUST be present and MUST be different from any other
    challenge. It can contain space characters no problem though

    An easy way to ensure your challenges are unique is to add a small unique
    prefix before the real name.
-->
<blockem_challenge name="tpl: Example 3">
    
    <!--
        Board specification  
    -->
    <board>
        <!-- 
            Number of rows of the board for this challenge.
            It MUST be a positive number (bigger than 0).
             Massive boards can be hard to hadle by blockem GUI, so be sensible 
        -->
        <nrows>15</nrows>
        <!-- 
            Number of comuns of the board for this challenge.
            It MUST be a positive number (bigger than 0).
            Massive boards can be hard to hadle by blockem GUI, so be sensible 
        -->
        <ncolumns>15</ncolumns>
    </board>
  
    <!-- 
        "opponent" represents a "virtual" player who can own squares on the
        board but never puts down a piece. It's the way a blockem challenge 
        sets squares to unavailable for the challenger.
        
        This tag MUST be present even if "opponent" does not have any 
        coordinate taken
    -->
    <opponent>
        <!--
            Each square on the board taken by 'opponent' player will be
            described using the taken tag:
                <taken row="N" col="M"/>
            
            Where row N and column M exist on the board. All squares are free
            by default until they are configured as taken by this tag
            
            WARNING: Bear in mind the first row or column is 0, and the latest
                     valid row or column is the amount of rows/columns defined
                     under the "board" tag minus 1
                     
            WARNING: Blockem won't load the challenge if the same square on the
                     board is taken by both opponent and challenger
        -->

        <taken row="0"  col="0" />
        <taken row="1"  col="1" />
        <taken row="2"  col="2" />
        <taken row="3"  col="3" />
        <taken row="4"  col="4" />
        <taken row="5"  col="5" />
        <taken row="6"  col="6"/>
        
        <taken row="8"  col="8"/>
        <taken row="9"  col="9"/>
        <taken row="10" col="10"/>
        <taken row="11" col="11"/>
        <taken row="12" col="12"/>
        <taken row="13" col="13"/>
        <taken row="14" col="14"/>
        
        <taken row="0"  col="14"/>
        <taken row="1"  col="13"/>
        <taken row="2"  col="12"/>
        <taken row="3"  col="11"/>
        <taken row="4"  col="10"/>
        <taken row="5"  col="9"/>
        <taken row="6"  col="8"/>
        
        <taken row="8"  col="6"/>
        <taken row="9"  col="5"/>
        <taken row="10" col="4"/>
        <taken row="11" col="3"/>
        <taken row="12" col="2"/>
        <taken row="13" col="1"/>
        <taken row="14" col="0"/>

    </opponent>
    
    <!-- 
        "challenger" represents the player who loads and plays the challenge.
        It defines:
            Squares already taken by him on the board
            Which pieces are available
            Starting coordinate
    -->
    <challenger>
        <!--
            Each square on the board taken by the challenger will be described
            using the 'taken' tag here:
                <taken row="N" col="M"/>
            
            Where row N and column M exist on the board. All squares are free
            by default until they are configured as taken by this tag
            
            WARNING: Bear in mind the first row or column is 0, and the latest
                     valid row or column is the amount of rows/columns defined
                     under the "board" tag minus 1
            
            WARNING: Blockem won't load the challenge if the same square on the
                     board is taken by both opponent and challenger
        -->
        
        <!--
            The following list contains the full set of available pieces in
            blockem. If a piece is available for the challenger the
            "available" tag should be set to "yes". Otherwise set it to "no"
            
            Default is NOT available, so if a piece is not found in one of these
            tags it won't be available
            
            Format of a piece tag is:
                <piece available="yes|no">piece's description</piece>
            
            Name of pieces is case sensitive and MUST be left as it is here
        -->
        <piece available="yes">Baby piece</piece> <!-- the only one available -->
        <piece available="yes">Two piece</piece>    
        <piece available="yes">Three piece</piece>
        <piece available="yes">Little V</piece>
        <piece available="yes">Full square</piece>
        <piece available="yes">Four long piece</piece>
        <piece available="yes">Little L</piece>
        <piece available="yes">Little S</piece>
        <piece available="yes">Little T</piece>
        <piece available="yes">Big long piece</piece>
        <piece available="yes">Square++</piece>
        <piece available="yes">Big V (aka Half square)</piece>
        <piece available="yes">U piece</piece>
        <piece available="yes">Big L</piece>
        <piece available="yes">Y piece</piece>
        <piece available="yes">Big S</piece>
        <piece available="yes">Mr T</piece>
        <piece available="yes">N piece (aka the ultimate)</piece>
        <piece available="yes">Saf piece</piece>
        <piece available="yes">W piece</piece>
        <piece available="yes">Cross piece</piece>
    
        <!--
            Starting row and starting column. This is an optional parameter:
            
              + MUST be set if the challenger has no taken squares on the board
              + If challenger has squares taken AND this starting coordinate is
                not set, the nucleation points generated by the taken squares
                will represent all possible starting points. You MUST ensure
                that there is at least one valid nucleation point or the 
                challenger won't be able to start            
              + If the challenger has squares taken and this option is set, 
                valid starting coordinates at the beginning of the challenge 
                will be all nucleation points plus the starting coordinate 
                described here
            
            You also must ensure this starting coordinate:
              + exists on the board,
              + is valid,
              + is not taken by either the opponent or the challenger itself,
              + does not belong to the forbidden area around challenger's taken
                squares.
            
            WARNING: Bear in mind the first row or column is 0, and the latest
                     valid row or column is the amount of rows/columns defined
                     under the "board" tag minus 1
        -->
        <starting_row>7</starting_row>
        <starting_col>7</starting_col>
    </challenger>
    
    <!--
        Miscellaneous data about this challenge
        
        This is an OPTIONAL tag. All tags contained in it are also OPTIONAL
    -->
    <infochallenge>
        <!-- 
            Author's name
        -->
        <author>Faustino Frechilla</author>
        <!--
            Author's e-mail 
        -->
        <email></email>
        <!-- 
            challenge description. 
            
            WARNING: It will be parsed with all new line and space characters
                     contained here
        -->
        <description>A funny-looking challenge in a 15x15 board</description>
    </infochallenge>
    
</blockem_challenge>

=== frechilla/blockem/src/tests/challengetest/challenge_valid1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE blockem_challenge SYSTEM "blockem_challenge.dtd">

<!--
    There is no real need for the previous line (locate the .dtd for this .xml
    file)
-->

<!--
    Attribute "name" MUST be present and MUST be different from any other
    challenge. It can contain space characters no problem though

    An easy way to ensure your challenges are unique is to add a small unique
    prefix before the real name.
-->
<blockem_challenge name="tst: Valid challenge 1">
    
    <!--
        Board specification  
    -->
    <board>
        <!-- 
            Number of rows of the board for this challenge.
            It MUST be a positive number (bigger than 0).
             Massive boards can be hard to hadle by blockem GUI, so be sensible 
        -->
        <nrows>14</nrows>
        <!-- 
            Number of comuns of the board for this challenge.
            It MUST be a positive number (bigger than 0).
            Massive boards can be hard to hadle by blockem GUI, so be sensible 
        -->
        <ncolumns>14</ncolumns>
    </board>
  
    <!-- 
        "opponent" represents a "virtual" player who can own squares on the
        board but never puts down a piece. It's the way a blockem challenge 
        sets squares to unavailable for the challenger.
        
        This tag MUST be present even if "opponent" does not have any 
        coordinate taken
    -->
    <opponent>
        <!--
            Each square on the board taken by 'opponent' player will be
            described using the taken tag:
                <taken row="N" col="M"/>
            
            Where row N and column M exist on the board. All squares are free
            by default until they are configured as taken by this tag
            
            WARNING: Bear in mind the first row or column is 0, and the latest
                     valid row or column is the amount of rows/columns defined
                     under the "board" tag minus 1
                     
            WARNING: Blockem won't load the challenge if the same square on the
                     board is taken by both opponent and challenger
        -->
        <taken row="0"  col="0"/>
        <taken row="0"  col="13"/>
        <taken row="13" col="0"/>
        <taken row="13"  col="13"/>
    </opponent>
    
    <!-- 
        "challenger" represents the player who loads and plays the challenge.
        It defines:
            Squares already taken by him on the board
            Which pieces are available
            Starting coordinate
    -->
    <challenger>
        <!--
            Each square on the board taken by the challenger will be described
            using the 'taken' tag here:
                <taken row="N" col="M"/>
            
            Where row N and column M exist on the board. All squares are free
            by default until they are configured as taken by this tag
            
            WARNING: Bear in mind the first row or column is 0, and the latest
                     valid row or column is the amount of rows/columns defined
                     under the "board" tag minus 1
            
            WARNING: Blockem won't load the challenge if the same square on the
                     board is taken by both opponent and challenger
        -->
        <taken row="1"  col="1"/>
        <taken row="1"  col="12"/>
        <taken row="12" col="1"/>
        <taken row="12"  col="12"/>
        <taken row="12"  col="12"/> <!-- warning: it's set as taken twice -->
        <taken row="6"  col="6"/>
        <taken row="6"  col="7"/>
        <taken row="7"  col="6"/>
        <taken row="7"  col="7"/>
        
        <!--
            The following list contains the full set of available pieces in
            blockem. If a piece is available for the challenger the
            "available" tag should be set to "yes". Otherwise set it to "no"
            
            Default is NOT available, so if a piece is not found in one of these
            tags it won't be available
            
            Format of a piece tag is:
                <piece available="yes|no">piece's description</piece>
            
            Name of pieces is case sensitive and MUST be left as it is here
        -->
        <piece available="no">Baby piece</piece>
        <piece available="yes">Two piece</piece>
        <piece available="yes">Three piece</piece>
        <piece available="yes">Little V</piece>
        <piece available="yes">Full square</piece>
        <piece available="yes">Four long piece</piece>
        <piece available="yes">Little L</piece>
        <piece available="yes">Little S</piece>
        <piece available="yes">Little T</piece>
        <piece available="yes">Big long piece</piece>
        <piece available="yes">Square++</piece>
        <piece available="yes">Big V (aka Half square)</piece>
        <piece available="yes">U piece</piece>
        <piece available="yes">Big L</piece>
        <piece available="yes">Y piece</piece>
        <piece available="yes">Big S</piece>
        <piece available="yes">Mr T</piece>
        <piece available="yes">N piece (aka the ultimate)</piece>
        <piece available="no">Saf piece</piece>
        <piece available="no">W piece</piece>
        <piece available="no">Cross piece</piece>
    
        <!--
            Starting row and starting column. This MUST be set since the 
            challenger will always be putting down pieces on the board
            
            Both row and column must exist on the board
            
            WARNING: Bear in mind the first row or column is 0, and the latest
                     valid row or column is the amount of rows/columns defined
                     under the "board" tag minus 1
        -->
        <starting_row>8</starting_row>
        <starting_col>8</starting_col>
    </challenger>
</blockem_challenge>

=== frechilla/blockem/challenges/example_challenge.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE blockem_challenge SYSTEM "blockem_challenge.dtd">

<!--
    There is no real need for the previous line (locate the .dtd for this .xml
    file)
-->

<!--
    Attribute name MUST be present and MUST be different from any other
    challenge. It can contain space characters no problem though

    An easy way to ensure your challenges are unique is to add a small unique
    prefix before the real name.
-->
<blockem_challenge name="tmpl: Example 1">
    
    <!--
        Board specification  
    -->
    <board>
        <!-- 
            Number of rows of the board for this challenge.
            It MUST be a positive number (bigger than 0).
             Massive boards can be hard to hadle by blockem GUI, so be sensible 
        -->
        <nrows>14</nrows>
        <!-- 
            Number of comuns of the board for this challenge.
            It MUST be a positive number (bigger than 0).
            Massive boards can be hard to hadle by blockem GUI, so be sensible 
        -->
        <ncolumns>14</ncolumns>
    </board>
  
    <!-- 
        There is always 2 players in a blockem challenge:
          + "challenger": Whoever loads the challenge to play it.
          + "opponent": Another player who can own spaces on the board, so they
                        don't belong to the challenger. It can be set up as
                        active (it also puts down pieces) or inactive through
                        the "active" tag (it can be set to "yes" or "no").
                        This extra player can be handled by the computer or
                        another human being when it is set up as active.
                        
        This "active" tag is MANDATORY (set it to "yes" or "no")
    -->
    <opponent active="no">
        <!--
            Each square on the board taken by 'opponent' player will be
            described using the taken tag:
                <taken row="N" col="M"/>
            
            Where row N and column M exist on the board. All squares are free
            by default until they are configured as taken by this tag
            
            WARNING: Bear in mind the first row or column is 0, and the latest
                     valid row or column is the amount of rows/columns defined
                     under the "board" tag minus 1
                     
            WARNING: Blockem won't load the challenge if the same square on the
                     board is taken by both opponent and challenger
        -->
        <taken row="4"  col="4"/>
        <taken row="5"  col="5"/>
        <taken row="10" col="10"/>
        
        <!--
            The following list contains the full set of available pieces in
            blockem. If a piece is available for the current player the
            "available" tag should be set to "yes". Otherwise set it to "no"
            Default is NOT available.
            
            The list of available pieces of this player is only used if it has 
            been set up as active (active="yes")
            
            Format of a piece tag is:
                <piece available="yes|no">piece's description</piece>
            
            Name of pieces is case sensitive and MUST be left as it is here
        -->
        <piece available="no">Baby piece</piece>
        <piece available="no">Two piece</piece>
        <piece available="no">Three piece</piece>
        <piece available="no">Little V</piece>
        <piece available="no">Full square</piece>
        <piece available="no">Four long piece</piece>
        <piece available="no">Little L</piece>
        <piece available="no">Little S</piece>
        <piece available="no">Little T</piece>
        <piece available="no">Big long piece</piece>
        <piece available="no">Square++</piece>
        <piece available="no">Big V (aka Half square)</piece>
        <piece available="no">U piece</piece>
        <piece available="no">Big L</piece>
        <piece available="no">Y piece</piece>
        <piece available="no">Big S</piece>
        <piece available="no">Mr T</piece>
        <piece available="no">N piece (aka the ultimate)</piece>
        <piece available="no">Saf piece</piece>
        <piece available="no">W piece</piece>
        <piece available="no">Cross piece</piece>
        
        <!--
            Starting row and starting column. This is only used if the player
            has been set to active (active="yes")
            
            Both row and column must exist on the board
            
            WARNING: Bear in mind the first row or column is 0, and the latest
                     valid row or column is the amount of rows/columns defined
                     under the "board" tag minus 1
                     
            WARNING: opponent's starting coordinate can not be the same as 
                     challenger's (if opponent is not active this coordinate
                     will be fully ignored)
            
            WARNING: If one of the tags is present, the other one MUST be 
                     present too
        -->
        <starting_row>0</starting_row>
        <starting_col>0</starting_col>
    </opponent>
    
    <!-- 
        challenger is always active, "active" tag can't be used as in 
        "opponent"
    -->
    <challenger>
        <!--
            Each square on the board taken by the challenger will be described
            using the 'taken' tag here:
                <taken row="N" col="M"/>
            
            Where row N and column M exist on the board. All squares are free
            by default until they are configured as taken by this tag
            
            WARNING: Bear in mind the first row or column is 0, and the latest
                     valid row or column is the amount of rows/columns defined
                     under the "board" tag minus 1
            
            WARNING: Blockem won't load the challenge if the same square on the
                     board is taken by both opponent and challenger
        -->
        <taken row="6"  col="6"/>
        <taken row="11" col="11"/>
        
        <!--
            The following list contains the full set of available pieces in
            blockem. If a piece is available for the challenger the
            "available" tag should be set to "yes". Otherwise set it to "no"
            
            Default is NOT available, so if a piece is not found in one of these
            tags it won't be available
            
            Format of a piece tag is:
                <piece available="yes|no">piece's description</piece>
            
            Name of pieces is case sensitive and MUST be left as it is here
        -->
        <piece available="yes">Baby piece</piece>
        <piece available="yes">Two piece</piece>
        <piece available="yes">Three piece</piece>
        <piece available="yes">Little V</piece>
        <piece available="yes">Full square</piece>
        <piece available="yes">Four long piece</piece>
        <piece available="yes">Little L</piece>
        <piece available="yes">Little S</piece>
        <piece available="yes">Little T</piece>
        <piece available="yes">Big long piece</piece>
        <piece available="yes">Square++</piece>
        <piece available="yes">Big V (aka Half square)</piece>
        <piece available="yes">U piece</piece>
        <piece available="yes">Big L</piece>
        <piece available="yes">Y piece</piece>
        <piece available="yes">Big S</piece>
        <piece available="yes">Mr T</piece>
        <piece available="yes">N piece (aka the ultimate)</piece>
        <piece available="yes">Saf piece</piece>
        <piece available="yes">W piece</piece>
        <piece available="yes">Cross piece</piece>
    
        <!--
            Starting row and starting column. This MUST be set since the 
            challenger will always be putting down pieces on the board
            
            Both row and column must exist on the board
            
            WARNING: Bear in mind the first row or column is 0, and the latest
                     valid row or column is the amount of rows/columns defined
                     under the "board" tag minus 1
            
            WARNING: opponent's starting coordinate can not be the same as 
                     challenger's (if opponent is not active this coordinate
                     will be fully ignored)
        -->
        <starting_row>0</starting_row>
        <starting_col>0</starting_col>
    </challenger>
</blockem_challenge>

=== frechilla/blockem/src/tests/challengetest/challenge_valid2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE blockem_challenge SYSTEM "blockem_challenge.dtd">

<blockem_challenge name="tst: Valid challenge 2">
    
    <board>
        <nrows>14</nrows>
        <ncolumns>14</ncolumns>
    </board>
  
    <opponent>
        <taken row="0"  col="0"/>
        <taken row="13" col="0"/>
        <taken row="13" col="0"/> <!-- warning: it's set as taken twice -->
    </opponent>
    
    <challenger>
        <taken row="6"  col="6"/>
        <taken row="6"  col="7"/>
        <taken row="7"  col="6"/>
        <taken row="7"  col="7"/>
        
        <piece available="yes">Baby piece</piece>
        <piece available="no">Two piece</piece>
        <piece available="no">Three piece</piece>
        <piece available="no">Little V</piece>
        <piece available="no">Full square</piece>
        <piece available="no">Four long piece</piece>
        <piece available="no">Little L</piece>
        <piece available="no">Little S</piece>
        <piece available="no">Little T</piece>
        <piece available="no">Big long piece</piece>
        <piece available="no">Square++</piece>
        <piece available="no">Big V (aka Half square)</piece>
        <piece available="no">U piece</piece>
        <piece available="no">Big L</piece>
        <piece available="no">Y piece</piece>
        <piece available="no">Big S</piece>
        <piece available="no">Mr T</piece>
        <piece available="no">N piece (aka the ultimate)</piece>
        <piece available="no">Saf piece</piece>
        <piece available="no">W piece</piece>
        <piece available="no">Cross piece</piece>
    
        <!-- starting coord is not set. Challenger will have to start off the
             nucleation points created by the taken squares -->
    </challenger>
</blockem_challenge>
